SHOW_GRAPHS = True
SHOW_FITTING_OUTPUT = 0 # 0=FALSE 1=TRUE
SHOW_EXAMPLES = False
NUMBER_EXAMPLES_SHOWN_TRAINING_SET = 10
PRINT_MODEL_SUMMARY = False

HIDDEN_LAYER_NEURONS_NUMBER = 400
OUTPUT_LAYER_NEURONS_NUMBER = 2

ADD_LEARNING_RATE_CALLBACK = False
ADD_EARLY_STOP_CALLBACK = False

SIGMOID = "sigmoid"
# SOFTMAX="softmax"
RANDOM_UNIFORM = "random_uniform"
TANH = "tanh"
LEARNING_RATE = 0.03
TEST_SIZE = 0.3
EPOCHS = 300
BATCH_SIZE = 400 #64